---
- name: Actualizar sistema en AlmaLinux
  hosts: 173.212.241.144
  become: true
  tasks:
    - name: Actualizar todos los paquetes
      dnf:
        name: "*"
        state: latest

    - name: Limpiar caché de paquetes
      command: dnf clean all
