---
- name: Actualizar sistemas CentOS y Rocky Linux
  hosts: 173.212.241.144
  become: yes
  tasks:
    - name: Actualizar todos los paquetes
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Limpiar paquetes obsoletos
      ansible.builtin.dnf:
        name: "*"
        state: absent
        autoremove: yes

    - name: Reiniciar si es necesario (solo si algún kernel o sistema crítico fue actualizado)
      ansible.builtin.reboot:
        reboot_timeout: 600
      when: ansible_facts['os_family'] == "RedHat" and ansible_facts['distribution'] in ["CentOS", "Rocky"]
