- name: Verificar Printer Spooler en SRV-WIN4600 (PowerShell 2.0)
  hosts: SRV-WIN4600
  gather_facts: no
  tasks:
    - name: Verificar estado del servicio Printer Spooler
      ansible.windows.win_command: 'sc query spooler'
      register: spooler_status

    - name: Mostrar estado del servicio
      debug:
        var: spooler_status.stdout_lines

    - name: Obtener cola de impresión (WMI)
      ansible.windows.win_command: 'powershell.exe -Command "Get-WmiObject -Query \"SELECT * FROM Win32_PrintJob\" | Select-Object Name, JobId, Status"'
      register: print_queue
      ignore_errors: yes

    - name: Mostrar cola de impresión
      debug:
        var: print_queue.stdout_lines