---
- name: Verificar y reiniciar CheckmkService (sin Telegram)
  hosts: all
  gather_facts: no
  become: false

  tasks:

    - name: Obtener estado del servicio CheckmkService
      win_shell: |
        Get-Service -Name CheckmkService | Select-Object Status | ConvertTo-Json
      register: service_raw

    - name: Convertir a variable Ansible
      set_fact:
        service_status: "{{ (service_raw.stdout | from_json).Status }}"

    - name: Mostrar estado actual del servicio
      debug:
        msg: "Estado actual de CheckmkService: {{ service_status }}"

    - name: Iniciar el servicio si está detenido
      win_service:
        name: CheckmkService
        start_mode: auto
        state: started
      when: service_status != 'Running'
      register: service_result

    - name: Mostrar resultado de iniciar el servicio
      debug:
        msg: >
          {% if service_status != 'Running' %}
          Servicio CheckmkService estaba detenido y se ha iniciado correctamente.
          {% else %}
          Servicio CheckmkService ya estaba en ejecución, no se hizo nada.
          {% endif %}
