---
- name: Probar conectividad Windows – ipconfig
  hosts: all
  gather_facts: no
  become: false

  tasks:

    - name: Ejecutar ipconfig
      win_shell: ipconfig /all
      register: ipconfig_result

    - name: Mostrar salida de ipconfig
      debug:
        msg: "{{ ipconfig_result.stdout }}"
