---
- name: Enviar notificación Artisteril por Telegram
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:

    ############################################################
    # 1️⃣ Normalizar variables recibidas del workflow
    ############################################################
    - name: Normalizar variables
      set_fact:
        telegram_service_status: "{{ telegram_service_status | default('DESCONOCIDO') }}"
        telegram_action: "{{ telegram_action | default('N/A') }}"
        telegram_port_connections: "{{ telegram_port_connections | default([]) }}"

    ############################################################
    # 2️⃣ Construir mensaje Telegram
    ############################################################
    - name: Construir mensaje
      set_fact:
        telegram_message: |
          🖥️ Servidor: SRV-AGVTCM01
          🔧 Servicio: Artisteril Tram Service
          📌 Estado: {{ telegram_service_status }}
          ⚙️ Acción: {{ telegram_action }}

          {% if telegram_port_connections | length > 0 %}
          🔴 Conexiones activas en puerto 10000:
          {% for line in telegram_port_connections %}
          {{ line }}
          {% endfor %}
          {% else %}
          🟢 No hay conexiones activas en el puerto 10000
          {% endif %}

    ############################################################
    # 3️⃣ Enviar mensaje a Telegram
    ############################################################
    - name: Enviar mensaje
      uri:
        url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_id }}"
          text: "{{ telegram_message }}"
        status_code: 200
