---
- name: Verificar servicio Artisteril Tram y conexiones puerto 10000
  hosts: SRV-AGVTCM01
  gather_facts: no
  become: false

  tasks:

    - name: Obtener estado del servicio Artisteril Tram Service
      win_shell: |
        Get-Service -Name "Artisteril Tram Service" |
        Select-Object Status |
        ConvertTo-Json
      register: service_raw

    - name: Convertir estado del servicio a variable
      set_fact:
        service_status: "{{ (service_raw.stdout | from_json).Status }}"

    - name: Verificar conexiones activas al puerto 10000
      win_shell: |
        NETSTAT.EXE -ano | findstr :10000
      register: netstat_10000
      failed_when: false
      changed_when: false

    - name: Determinar si hay conexiones al puerto 10000
      set_fact:
        hay_conexiones_10000: "{{ netstat_10000.stdout | length > 0 }}"

    - name: Reiniciar servidor si NO hay conexiones al puerto 10000
      win_reboot:
        reboot_timeout: 900
        msg: "Reinicio autom치tico: no hay conexiones activas en el puerto 10000"
      when: not hay_conexiones_10000
      register: reboot_result

    - name: Exportar datos para notificaci칩n Telegram
      set_stats:
        data:
          telegram_service_status: "{{ service_status }}"
          telegram_reinicio: "{{ not hay_conexiones_10000 }}"
          telegram_action: >-
            {% if not hay_conexiones_10000 %}
            游댮 Servidor reiniciado autom치ticamente (sin conexiones en puerto 10000)
            {% else %}
            游릭 Servidor NO reiniciado (hay conexiones activas)
            {% endif %}
          telegram_port_connections: "{{ netstat_10000.stdout_lines | default([]) }}"

    - name: Mostrar resultado final
      debug:
        msg:
          - "Estado servicio: {{ service_status }}"
          - "Conexiones puerto 10000: {{ hay_conexiones_10000 }}"
          - "Reinicio ejecutado: {{ not hay_conexiones_10000 }}"
