---
- name: Verificar servicio Artisteril Tram y conexiones puerto 10000
  hosts: SRV-AGVTCM01
  gather_facts: no
  become: false

  tasks:

    - name: Obtener estado del servicio Artisteril Tram Service
      win_shell: |
        Get-Service -Name "Artisteril Tram Service" |
        Select-Object Status |
        ConvertTo-Json
      register: service_raw

    - name: Convertir estado del servicio a variable
      set_fact:
        service_status: "{{ (service_raw.stdout | from_json).Status }}"

    - name: Verificar conexiones activas al puerto 10000
      win_shell: |
        NETSTAT.EXE -ano | findstr :10000
      register: netstat_10000
      failed_when: false
      changed_when: false

    - name: Determinar si hay conexiones al puerto 10000
      set_fact:
        hay_conexiones_10000: "{{ netstat_10000.stdout | length > 0 }}"

    - name: Iniciar el servicio si está detenido y sin conexiones
      win_service:
        name: Artisteril Tram Service
        start_mode: auto
        state: started
      when:
        - service_status != 'Running'
        - not hay_conexiones_10000

    - name: Exportar datos para notificación Telegram
      set_stats:
        data:
          telegram_service_status: "{{ service_status }}"
          telegram_action: >-
            {% if hay_conexiones_10000 %}
            Servicio NO modificado (conexiones activas)
            {% elif service_status != 'Running' %}
            Servicio iniciado
            {% else %}
            Sin cambios
            {% endif %}
          telegram_port_connections: "{{ netstat_10000.stdout_lines | default([]) }}"

    - name: Mostrar resultado final
      debug:
        msg:
          - "Estado servicio: {{ service_status }}"
          - "Conexiones puerto 10000: {{ hay_conexiones_10000 }}"
