---
- name: Actualizar sistema operativo según distribución
  hosts: all
  become: true

  tasks:

    - name: Detectar distribución
      ansible.builtin.debug:
        msg: "Distribución detectada: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"

    - name: Actualizar Debian/Ubuntu
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Actualizar RedHat/CentOS/Alma/Rocky
      ansible.builtin.yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"

    - name: Actualizar Fedora
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_distribution == "Fedora"

    - name: Actualizar Arch Linux
      ansible.builtin.pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_distribution == "Archlinux"
