---
- name: Instalar y configurar Zabbix Agent
  hosts: all
  become: yes

  vars:
    zabbix_server: "172.40.10.6"
    zabbix_agent_conf: /etc/zabbix_agentd.conf

  tasks:
    - name: Instalar repositorio de Zabbix (RHEL/CentOS)
      yum:
        name: "https://repo.zabbix.com/zabbix/7.0/rocky/9/x86_64/zabbix-release-latest.el9.noarch.rpm"
        state: present
        disable_gpg_check: true
      when: ansible_os_family == "RedHat"

    - name: Instalar Zabbix Agent
      package:
        name: zabbix-agent
        state: present

    - name: Configurar el servidor de Zabbix en zabbix_agentd.conf
      lineinfile:
        path: "{{ zabbix_agent_conf }}"
        regexp: '^Server='
        line: "Server={{ zabbix_server }}"
      notify: restart zabbix agent

    - name: Configurar el servidor activo en zabbix_agentd.conf
      lineinfile:
        path: "{{ zabbix_agent_conf }}"
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server }}"
      notify: restart zabbix agent

    - name: Iniciar y habilitar el servicio de Zabbix Agent
      systemd:
        name: zabbix-agent
        enabled: yes
        state: started

  handlers:
    - name: restart zabbix agent
      systemd:
        name: zabbix-agent
        state: restarted