- name: Shutdown interface via telnet
  ansible.builtin.expect:
    command: "telnet {{ huawei_host }}"
    timeout: 30
    responses:
      "Username:": "{{ huawei_user }}"
      "Password:": "{{ huawei_pass }}"

      "<.*>":
        - "system-view"
        - "quit"   # 👈 IMPORTANTE (para cerrar sesión)

      "\\[.*\\]":
        - "interface GigabitEthernet0/0/5"
        - "shutdown"
        - "return"
    echo: yes
