---
- name: Huawei S5720 interface control
  hosts: huawei
  gather_facts: no

  tasks:

    - name: Shutdown interface
      community.network.ce_config:
        lines:
          - interface GigabitEthernet0/0/5
          - shutdown

    - name: Wait 10 seconds
      ansible.builtin.pause:
        seconds: 10

    - name: Undo shutdown
      community.network.ce_config:
        lines:
          - interface GigabitEthernet0/0/5
          - undo shutdown
