---
- name: Actualización automática de CyberPanel sin interacción
  hosts: srv-cpweb02
  become: yes
  tasks:

    - name: Instalar expect
      package:
        name: expect
        state: present

    - name: Ejecutar actualización de CyberPanel sin interacción
      expect:
        command: >
          bash -c "sh <(curl -fsSL https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh
          || wget -O - https://raw.githubusercontent.com/usmannasir/cyberpanel/stable/preUpgrade.sh)"
        responses:
          'Press Enter to continue': ''
          'Do you want to continue.*': 'y'
          'Are you sure.*': 'y'
          'Continue.*': 'y'
        timeout: 3600
      register: cyberpanel_upgrade

    - name: Mostrar salida
      debug:
        var: cyberpanel_upgrade.stdout
