---
- name: Verificar, crear y permitir VLAN en Huawei Core (completo)
  hosts: core-sw
  gather_facts: no

  vars:
    trunk_interface: Eth-Trunk1

  tasks:
    - name: Verificar si la VLAN {{ vlan_id }} existe
      ansible.netcommon.cli_command:
        command: "display vlan {{ vlan_id }}"
      register: vlan_check
      ignore_errors: yes

    - name: Crear VLAN si no existe
      when: "'does not exist' in vlan_check.stdout | join(' ')"
      ansible.netcommon.cli_config:
        lines:
          - vlan {{ vlan_id }}
          - description {{ vlan_name }}

    - name: Verificar configuración del trunk
      ansible.netcommon.cli_command:
        command: "display current-configuration interface {{ trunk_interface }}"
      register: trunk_config

    - name: Agregar VLAN al trunk si no está permitida (solo si no está la VLAN ni está permitido 'all')
      when: >
        ('vlan all' not in trunk_config.stdout | join(' ')) and
        ('vlan {{ vlan_id }}' not in trunk_config.stdout | join(' '))
      ansible.netcommon.cli_config:
        parents: ["interface {{ trunk_interface }}"]
        lines:
          - port trunk allow-pass vlan {{ vlan_id }}

    - name: Mostrar estado del trunk
      debug:
        msg: >
          {% if 'vlan all' in trunk_config.stdout | join(' ') %}
            La interfaz {{ trunk_interface }} ya permite todas las VLANs (vlan all).
          {% elif 'vlan ' ~ vlan_id in trunk_config.stdout | join(' ') %}
            La VLAN {{ vlan_id }} ya está permitida en el trunk {{ trunk_interface }}.
          {% else %}
            Se ha agregado la VLAN {{ vlan_id }} al trunk {{ trunk_interface }}.
          {% endif %}
