---
- name: Verificar y configurar VLAN y puerto en switch Huawei
  hosts: "{{ target_switch }}"
  gather_facts: no
  vars_prompt: []

  tasks:

    - name: Verificar si la VLAN {{ vlan_id }} existe
      ansible.netcommon.cli_command:
        command: "display vlan {{ vlan_id }}"
      register: vlan_check
      ignore_errors: yes

    - name: Crear VLAN si no existe
      when: "'does not exist' in vlan_check.stdout | join(' ')"
      ansible.netcommon.cli_config:
        lines:
          - vlan {{ vlan_id }}
          - description {{ vlan_name }}

    - name: Verificar configuración del trunk {{ trunk_interface }}
      ansible.netcommon.cli_command:
        command: "display current-configuration interface {{ trunk_interface }}"
      register: trunk_config

    - name: Agregar VLAN al trunk si no está permitida
      when: >
        ('vlan all' not in trunk_config.stdout | join(' ')) and
        ('vlan {{ vlan_id }}' not in trunk_config.stdout | join(' '))
      ansible.netcommon.cli_config:
        parents: ["interface {{ trunk_interface }}"]
        lines:
          - port trunk allow-pass vlan {{ vlan_id }}

    - name: Mostrar estado del trunk
      debug:
        msg: >
          {% if 'vlan all' in trunk_config.stdout | join(' ') %}
            El trunk {{ trunk_interface }} ya permite todas las VLANs (vlan all).
          {% elif 'vlan ' ~ vlan_id in trunk_config.stdout | join(' ') %}
            La VLAN {{ vlan_id }} ya está permitida en el trunk {{ trunk_interface }}.
          {% else %}
            Se ha agregado la VLAN {{ vlan_id }} al trunk {{ trunk_interface }}.
          {% endif %}

    - name: Verificar configuración del puerto {{ target_port }}
      ansible.netcommon.cli_command:
        command: "display current-configuration interface {{ target_port }}"
      register: port_config

    - name: Configurar puerto {{ target_port }} como access si no pertenece a la VLAN {{ vlan_id }}
      when: "'port default vlan {{ vlan_id }}' not in port_config.stdout | join(' ')"
      ansible.netcommon.cli_config:
        parents: ["interface {{ target_port }}"]
        lines:
          - port link-type access
          - port default vlan {{ vlan_id }}
          - undo shutdown

    - name: Mostrar estado del puerto
      when: "'port default vlan {{ vlan_id }}' in port_config.stdout | join(' ')"
      debug:
        msg: "El puerto {{ target_port }} ya pertenece a la VLAN {{ vlan_id }}, no se realizaron cambios."

    - name: Guardar configuración persistente
      ansible.netcommon.cli_command:
      command: save -y

