---
- name: Mantenimiento basico WordPress
  hosts: srv-cpweb02
  become: yes
  vars:
    wp_base_path: /home
    wp_bin: /usr/local/bin/wp

    wp_sites:
      - domain: algry.com
        user: algry9302
      - domain: bodegasduron.com
        user: bodeg3787
      - domain: nutribenprofesionales.es
        user: nutri8393

  tasks:

    - name: Comprobar si WP-CLI esta instalado
      stat:
        path: "{{ wp_bin }}"
      register: wpcli_bin

    - name: Descargar e instalar WP-CLI
      get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: "{{ wp_bin }}"
        mode: '0755'
      when: not wpcli_bin.stat.exists

    - name: Activar mantenimiento
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} maintenance-mode activate
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"
      failed_when: false

    - name: Actualizar WordPress core
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} core update
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"

    - name: Actualizar base de datos WordPress
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} core update-db
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"
      failed_when: false

    - name: Actualizar plugins
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} plugin update --all
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"

    - name: Actualizar themes
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} theme update --all
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"

    - name: Desactivar mantenimiento (siempre)
      shell: |
        sudo -H -u {{ item.user }} {{ wp_bin }} maintenance-mode deactivate
      args:
        chdir: "{{ wp_base_path }}/{{ item.domain }}/public_html"
      loop: "{{ wp_sites }}"
      failed_when: false

