---
- name: Verificar y reiniciar "Artisteril Tram Service"
  hosts: all
  gather_facts: no
  become: false

  tasks:

    - name: Obtener estado del servicio Artisteril Tram Service
      win_shell: |
        Get-Service -Name "Artisteril Tram Service" | Select-Object Status | ConvertTo-Json
      register: service_raw

    - name: Convertir a variable Ansible
      set_fact:
        service_status: "{{ (service_raw.stdout | from_json).Status }}"

    - name: Mostrar estado actual del servicio
      debug:
        msg: "Estado actual de Artisteril Tram Service: {{ service_status }}"

    - name: Iniciar el servicio si está detenido
      win_service:
        name: Artisteril Tram Service
        start_mode: auto
        state: started
      when: service_status != 'Running'
      register: service_result

    - name: Mostrar resultado de iniciar el servicio
      debug:
        msg: >
          {% if service_status != 'Running' %}
          Servicio Artisteril Tram estaba detenido y se ha iniciado correctamente.
          {% else %}
          Servicio Artisteril Tram ya estaba en ejecución, no se hizo nada.
          {% endif %}
