---
- name: Traer archivos de máquinas no registradas a servidor Linux intermedio
  hosts: srv-ddc01
  gather_facts: no
  become: false

  vars:
    remote_base_path: "/opt/almacen-de-reporte/data"

  tasks:
    - name: Copiar archivo de Windows a servidor intermedio
      delegate_to: "{{ report_host:report_port }}"
      fetch:
        src: C:\Temp\unregistered_machines.txt
        dest: "{{ remote_base_path }}/unregistered_machines_{{ inventory_hostname }}.txt"
        flat: yes
