---
- name: Traer archivo desde Windows al contenedor de reportes
  hosts: srv-ddc01
  gather_facts: no
  become: false

  vars:
    contenedor_path: "/opt/almacen-de-reporte/data/unregistered_machines_{{ inventory_hostname }}.txt"

  tasks:
    - name: Copiar archivo de Windows al host de AWX
      fetch:
        src: C:\Temp\unregistered_machines.txt
        dest: "{{ contenedor_path }}"
        flat: yes