---
- name: Leer archivo en Windows
  hosts: srv-ddc01
  gather_facts: no

  vars:
    archivo_origen: C:\Temp\unregistered_machines.txt

  tasks:
    - name: Leer archivo y codificarlo en Base64
      win_shell: |
        [Convert]::ToBase64String(
          [System.IO.File]::ReadAllBytes("{{ archivo_origen }}")
        )
      register: archivo_b64

    - name: Guardar Base64 como fact
      set_fact:
        archivo_base64: "{{ archivo_b64.stdout }}"

- name: Guardar archivo en controller (localhost)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Escribir archivo Base64 en disco
      copy:
        content: "{{ hostvars['srv-ddc01'].archivo_base64 }}"
        dest: /tmp/unregistered_machines.b64

- name: Crear archivo final en srv-ansible
  hosts: srv-ansible
  become: true
  gather_facts: no

  vars:
    archivo_destino: /opt/almacen-de-reporte/unregistered_machines.txt

  tasks:
    - name: Decodificar y crear archivo
      copy:
        content: "{{ lookup('file', '/tmp/unregistered_machines.b64') | b64decode }}"
        dest: "{{ archivo_destino }}"
        owner: root
        group: root
        mode: '0644'
