---
- name: Leer archivo en Windows
  hosts: srv-ddc01
  gather_facts: no

  vars:
    archivo_origen: C:\Temp\unregistered_machines.txt

  tasks:
    - name: Leer archivo y codificarlo en Base64
      win_shell: |
        [Convert]::ToBase64String(
          [System.IO.File]::ReadAllBytes("{{ archivo_origen }}")
        )
      register: archivo_b64

    - name: Guardar Base64 como fact
      set_fact:
        archivo_base64: "{{ archivo_b64.stdout }}"

- name: Crear archivo en servidor Linux (srv-ansible)
  hosts: 192.168.71.235
  gather_facts: no
  become: true

  vars:
    ansible_connection: ssh
    ansible_user: root          # ajusta si usas otro usuario
    archivo_destino: /opt/almacen-de-reporte/unregistered_machines.txt

  tasks:
    - name: Crear archivo desde Base64 recibido de Windows
      copy:
        content: "{{ hostvars['srv-ddc01'].archivo_base64 | b64decode }}"
        dest: "{{ archivo_destino }}"
        owner: root
        group: root
        mode: '0644'
