- name: Copiar archivo Windows a srv-ansible
  hosts: srv-ddc01
  gather_facts: no

  tasks:
    - name: Traer archivo a controller
      win_fetch:
        src: C:\Temp\unregistered_machines.txt
        dest: /tmp/unregistered_machines.txt
        flat: yes
      delegate_to: localhost

    - name: Enviar archivo a srv-ansible
      copy:
        src: /tmp/unregistered_machines.txt
        dest: /opt/almacen-de-reporte/unregistered_machines.txt
      delegate_to: srv-ansible
