---
- name: Generar reporte Citrix no registradas y enviar por Telegram
  hosts: srv-ddc01
  gather_facts: no
  become: false

  vars:
    report_tmp_dir: "/tmp/reportes"
    report_file: "citrix_no_registradas.txt"

  tasks:

    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered.Count -gt 0) {
            $lines = @()
            foreach ($m in $unregistered) {
                $lines += "🖥 $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
            }
            $lines -join "`n"
        } else {
            "✅ Todas las máquinas están registradas"
        }
      register: citrix_output

    - name: Crear directorio temporal en AWX
      delegate_to: localhost
      file:
        path: "{{ report_tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Crear archivo de reporte en AWX
      delegate_to: localhost
      copy:
        content: "{{ citrix_output.stdout }}"
        dest: "{{ report_tmp_dir }}/{{ report_file }}"

    - name: Enviar reporte por Telegram
      delegate_to: localhost
      community.general.telegram:
        token: "{{ telegram_bot_token }}"
        chat_id: "{{ telegram_chat_id }}"
        message: |
          📊 *Reporte Citrix – Máquinas no registradas*
          🕒 {{ ansible_date_time.date }} {{ ansible_date_time.time }}

          {{ citrix_output.stdout }}
        parse_mode: markdown