---
- name: Generar reporte Citrix no registradas
  hosts: srv-ddc01
  gather_facts: no
  become: false

  tasks:

    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered.Count -gt 0) {
            $lines = @()
            foreach ($m in $unregistered) {
                $ip = if ($m.IPAddress) { $m.IPAddress } else { "-" }
                $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState) | IP: $ip"
            }
            $lines -join "`n"
        } else {
            "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Debug - mostrar contenido generado
      debug:
        msg: "{{ unregistered_machines.stdout }}"

    - name: Guardar artifact para workflow
      copy:
        content: "{{ unregistered_machines.stdout | default('ALL_REGISTERED') }}"
        dest: "/tmp/unregistered_machines.txt"
      delegate_to: localhost
