---
- name: Obtener máquinas Citrix no registradas (Windows)
  hosts: srv-ddc01
  gather_facts: no
  become: false

  tasks:

    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue
        if ($unregistered.Count -gt 0) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "✅ Todas las máquinas están registradas"
        }
      register: citrix_output

    - name: Guardar reporte en variable para workflow
      set_fact:
        citrix_reporte: "{{ citrix_output.stdout }}"
      # Marcar en AWX: Output Variable -> citrix_reporte
