---
###############################################################################
# PLAY 1 – Windows: generar el contenido
###############################################################################
- name: Generar reporte de máquinas Citrix no registradas (Windows)
  hosts: srv-ddc01
  gather_facts: no

  tasks:
    - name: Obtener máquinas sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Exponer contenido al controller
      set_fact:
        report_content: "{{ unregistered_machines.stdout }}"

###############################################################################
# PLAY 2 – Controller AWX (Linux real, sin copy)
###############################################################################
- name: Guardar reporte en el controller AWX
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    report_path: "/opt/unregistered_machines.txt"

  tasks:
    - name: Crear directorio destino
      shell: |
        mkdir -p /opt
      args:
        executable: /bin/sh

    - name: Escribir archivo directamente en el controller
      shell: |
        cat << 'EOF' > {{ report_path }}
        {{ hostvars['srv-ddc01'].report_content }}
        EOF
      args:
        executable: /bin/sh
