---
- name: Generar reporte Citrix y enviar por Telegram
  hosts: srv-ddc01
  gather_facts: no

  vars:
    telegram_bot_token: "7327847658:AAE5Fi5iE4pyiMZaWuDvp7esggUvYH2x3Cs"
    telegram_chat_id: "7883793545"

  tasks:
    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Guardar reporte como artifact
      set_stats:
        data:
          unregistered_machines_report: "{{ unregistered_machines.stdout }}"
        aggregate: false

    - name: Enviar reporte por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ hostvars['srv-ddc01'].unregistered_machines.stdout | default('ALL_REGISTERED') }}"
        status_code: 200
