- name: Generar archivo y copiarlo al controller
  hosts: srv-ddc01
  gather_facts: no

  vars:
    windows_tmp_file: "C:\\Temp\\unregistered_machines.txt"
    controller_dest: "/tmp/unregistered_machines.txt"

  tasks:
    - name: Obtener máquinas sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Guardar archivo en Windows
      win_copy:
        content: "{{ unregistered_machines.stdout }}"
        dest: "{{ windows_tmp_file }}"

    - name: Copiar archivo al controller (AWX)
      copy:
        content: "{{ unregistered_machines.stdout }}"
        dest: "{{ controller_dest }}"
      delegate_to: localhost
