---
- name: Detectar VMs Citrix NO registradas
  hosts: SRV-DDC01
  gather_facts: no
  become: false

  tasks:

    - name: Obtener máquinas Citrix no registradas
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue

        $machines = Get-BrokerMachine -RegistrationState Unregistered |
          Select-Object MachineName, PowerState

        $result = @{
          powered_on = @()
          restarted  = @()
          skipped    = @()
        }

        foreach ($m in $machines) {
          # Limpiar nombre (sin dominio)
          $cleanName = if ($m.MachineName -match "\\") { ($m.MachineName -split "\\")[-1] } else { $m.MachineName }

          # Guardar nombres según estado para Job2
          if ($m.PowerState -eq "Off") {
            $result.powered_on += $cleanName
          }
          elseif ($m.PowerState -eq "On") {
            $result.restarted += $cleanName
          }
          else {
            $result.skipped += $cleanName
          }
        }

        $result | ConvertTo-Json -Depth 3
      register: citrix_actions

    - name: Convertir resultado a variable Ansible
      set_fact:
        citrix_result: "{{ citrix_actions.stdout | from_json }}"

    - name: Exportar resultado para AWX Workflow
      set_stats:
        data:
          citrix_powered_on: "{{ citrix_result.powered_on }}"
          citrix_restarted: "{{ citrix_result.restarted }}"
          citrix_skipped: "{{ citrix_result.skipped }}"

    - name: Mostrar resumen
      debug:
        msg:
          - "🟢 Encendidas: {{ citrix_result.powered_on | length }}"
          - "🔁 Encendidas pero no registradas: {{ citrix_result.restarted | length }}"
          - "⚠️ Omitidas: {{ citrix_result.skipped | length }}"
