---
###############################################################################
# PLAY ÚNICO – Windows + Controller (delegación correcta)
###############################################################################
- name: Generar reporte Citrix y guardarlo en el controller AWX
  hosts: srv-ddc01
  gather_facts: no

  vars:
    report_path: "/opt/unregistered_machines.txt"

  tasks:
    - name: Obtener máquinas sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Crear directorio /opt en el controller
      shell: mkdir -p /opt
      delegate_to: 127.0.0.1
      vars:
        ansible_connection: local
        ansible_shell_type: sh
        ansible_python_interpreter: /usr/bin/python3
      run_once: true

    - name: Escribir archivo en el controller AWX
      shell: |
        cat << 'EOF' > {{ report_path }}
        {{ unregistered_machines.stdout }}
        EOF
      delegate_to: 127.0.0.1
      vars:
        ansible_connection: local
        ansible_shell_type: sh
        ansible_python_interpreter: /usr/bin/python3
      run_once: true
