---
- name: Obtener máquinas Citrix no registradas (Windows)
  hosts: srv-ddc01
  gather_facts: no
  become: false

  vars:
    report_tmp_dir: "/tmp/reportes"
    report_file: "citrix_no_registradas.txt"

  tasks:

    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue
        if ($unregistered.Count -gt 0) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "✅ Todas las máquinas están registradas"
        }
      register: citrix_output

    - name: Crear directorio temporal en AWX
      delegate_to: localhost
      run_once: true
      file:
        path: "{{ report_tmp_dir }}"
        state: directory
        mode: '0755'

    - name: Guardar reporte temporal
      delegate_to: localhost
      run_once: true
      copy:
        content: "{{ citrix_output.stdout }}"
        dest: "{{ report_tmp_dir }}/{{ report_file }}"
