---
- name: Generar reporte Citrix no registradas (Windows)
  hosts: srv-ddc01
  gather_facts: no

  tasks:
    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Guardar reporte como artifact
      set_stats:
        data:
          unregistered_machines_report: "{{ unregistered_machines.stdout }}"
        aggregate: false
