---
- name: Generar reporte Citrix no registradas
  hosts: srv-ddc01
  gather_facts: no
  become: true

  tasks:

    - name: Obtener máquinas Citrix sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered.Count -gt 0) {
            $lines = @()
            foreach ($m in $unregistered) {
                $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState)"
            }
            $lines -join "`n"
        } else {
            "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Guardar reporte en Windows
      win_copy:
        content: "{{ unregistered_machines.stdout }}"
        dest: C:\Temp\citrix_unregistered.txt

    - name: Copiar reporte desde Windows a Linux
      fetch:
        src: C:\Temp\citrix_unregistered.txt
        dest: /opt/reportes/citrix_unregistered_{{ inventory_hostname }}.txt
        flat: yes

