---
- name: Enviar reporte de máquinas Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    local_tmp_file: "/tmp/unregistered_machines_srv-ddc01.txt"
    current_time: "{{ '%Y-%m-%d %H:%M' | strftime }}"

  tasks:
    - name: Leer contenido del archivo
      set_fact:
        machines_text: "{{ lookup('file', local_tmp_file) | trim }}"

    - name: Enviar alerta si hay máquinas sin registrar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ⚠️ Citrix - Máquinas NO registradas
            Servidor: srv-ddc01
            Fecha: {{ current_time }}

            {{ machines_text }}
        status_code: 200
      when: machines_text != "ALL_REGISTERED"

    - name: Enviar OK si todas están registradas
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ✅ Citrix OK
            Todas las máquinas están registradas correctamente.
            Servidor: srv-ddc01
            Fecha: {{ current_time }}
        status_code: 200
      when: machines_text == "ALL_REGISTERED"
