---
- name: Enviar reporte Citrix a Telegram
  hosts: localhost
  gather_facts: no
  vars:
    telegram_bot_token: "{{ telegram_bot_token }}"
    telegram_chat_id: "{{ telegram_chat_id }}"
  tasks:

    - name: Leer contenido del archivo
      slurp:
        src: /tmp/unregistered_machines_srv-ddc01.txt
      register: file_content

    - name: Decodificar contenido del archivo
      set_fact:
        unregistered_machines: "{{ file_content.content | b64decode }}"

    - name: Enviar alerta por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            {% if 'Todas las máquinas están registradas' in unregistered_machines %}
            ✅ Citrix OK - Todas las máquinas están registradas
            {% else %}
            ⚠️ Citrix - Máquinas NO registradas
            {{ unregistered_machines }}
            {% endif %}
