---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    citrix_reporte: ""

  tasks:

    - name: Obtener fecha y hora actual en UTC
      set_fact:
        current_utc: "{{ lookup('pipe','date -u \"+%Y-%m-%d %H:%M:%S\"') }}"

    - name: Ajustar hora a UTC+1 (España)
      set_fact:
        current_datetime: "{{ (current_utc | to_datetime('%Y-%m-%d %H:%M:%S') + timedelta(hours=1)) | strftime('%Y-%m-%d %H:%M:%S') }}"

    - name: Preparar texto del mensaje
      set_fact:
        telegram_message: |
          📊 Reporte Citrix – Máquinas no registradas
          🕒 {{ current_datetime }}

          {{ citrix_reporte }}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
        status_code: 200
