---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    report_tmp_dir: "/tmp/reportes"
    report_file: "citrix_no_registradas.txt"

  tasks:

    - name: Leer reporte temporal
      slurp:
        src: "{{ report_tmp_dir }}/{{ report_file }}"
      register: reporte_raw

    - name: Convertir reporte a texto
      set_fact:
        reporte_texto: |
          📊 Reporte Citrix – Máquinas no registradas
          🕒 {{ ansible_date_time.date }} {{ ansible_date_time.time }}

          {{ reporte_raw.content | b64decode }}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ reporte_texto }}"
        status_code: 200
