---
- name: Enviar reporte de Citrix por Telegram
  hosts: srv-ddc01
  gather_facts: no
  tasks:

    - name: Leer archivo de maquinas no registradas
      win_shell: type C:\Temp\unregistered_machines.txt
      register: unregistered_machines
      changed_when: false

    - name: Enviar alerta por Telegram si hay maquinas sin registrar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            {% if unregistered_machines.stdout != '' %}
            ⚠️ Citrix - Máquinas NO registradas
            {{ unregistered_machines.stdout }}
            {% else %}
            ✅ Citrix OK - Todas las máquinas están registradas
            {% endif %}
      delegate_to: localhost
