---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Revisar artifact recibido
      debug:
        msg: "Artifact del workflow: {{ workflow_artifacts['unregistered_machines_report'] }}"

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ workflow_artifacts['unregistered_machines_report'] }}"
        status_code: 200
