---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    tz: "Europe/Madrid"

  tasks:

    - name: Obtener fecha y hora (España - Linux estándar)
      set_fact:
        current_datetime: "{{ lookup('pipe', 'TZ=' ~ tz ~ ' date +\"%d-%m-%Y %H:%M:%S\"') }}"

    - name: Normalizar variables (por seguridad)
      set_fact:
        citrix_powered_on: "{{ citrix_powered_on | default([]) }}"
        citrix_restarted: "{{ citrix_restarted | default([]) }}"
        citrix_skipped: "{{ citrix_skipped | default([]) }}"

    - name: Determinar si hay VMs que reportar
      set_fact:
        tiene_reporte: "{{ (citrix_powered_on | length > 0) or (citrix_restarted | length > 0) or (citrix_skipped | length > 0) }}"

    - name: Construir mensaje de VMs no registradas o apagadas
      set_fact:
        telegram_message: >-
          {% if not tiene_reporte %}
          ✅ Todas los servidores citrix están registrodas
          {% else %}
          📊 Reporte Citrix – Máquinas no registradas o apagadas
          🕒 {{ current_datetime }}

          {% if citrix_powered_on | length > 0 %}
          🔌 Máquinas encendidas ({{ citrix_powered_on | length }}):
          {{ citrix_powered_on | join('\n') }}
          {% endif %}

          {% if citrix_restarted | length > 0 %}
          🔁 Máquinas reiniciadas ({{ citrix_restarted | length }}):
          {{ citrix_restarted | join('\n') }}
          {% endif %}

          {% if citrix_skipped | length > 0 %}
          ⚠️ Máquinas omitidas ({{ citrix_skipped | length }}):
          {{ citrix_skipped | join('\n') }}
          {% endif %}
          {% endif %}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
        status_code: 200


