---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    # Variable recibida desde Job 1 vía Workflow
    citrix_reporte: ""

  tasks:

    - name: Preparar texto del mensaje
      set_fact:
        telegram_message: |
          📊 Reporte Citrix – Máquinas no registradas
          🕒 {{ ansible_date_time.date }} {{ ansible_date_time.time }}

          {{ citrix_reporte }}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
        status_code: 200
