---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    citrix_reporte: ""

  tasks:

    - name: Obtener fecha y hora actual en España (UTC+1)
      set_fact:
        current_datetime: "{{ lookup('pipe','TZ=Europe/Madrid date \"+%d-%m-%Y %H:%M:%S\"') }}"

    - name: Preparar texto del mensaje
      set_fact:
        telegram_message: |
          📊 Reporte Citrix – Máquinas no registradas
          🕒 {{ current_datetime }}

          {{ citrix_reporte }}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
        status_code: 200
