---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no  # No necesitamos recopilar facts

  vars:
    # Variable recibida desde Job 1 vía Workflow
    citrix_reporte: ""

  tasks:

    - name: Obtener fecha y hora actual del sistema Linux
      set_fact:
        current_datetime: "{{ lookup('pipe','date -u \"+%Y-%m-%d %H:%M:%S\"') | to_datetime('%Y-%m-%d %H:%M:%S') | community.general.to_datetime_string('%Y-%m-%d %H:%M:%S', tz='Europe/Madrid') }}"

    - name: Preparar texto del mensaje
      set_fact:
        telegram_message: |
          📊 Reporte Citrix – Máquinas no registradas
          🕒 {{ current_datetime }}

          {{ citrix_reporte }}

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
        status_code: 200
