---
- name: Enviar reporte de máquinas Citrix por Telegram
  hosts: localhost
  gather_facts: no

  vars:
    # Ruta local del archivo traído desde Windows
    local_tmp_file: "/tmp/unregistered_machines.txt"
    current_time: "{{ '%Y-%m-%d %H:%M' | strftime }}"

  tasks:
    - name: Verificar que el archivo existe
      stat:
        path: "{{ local_tmp_file }}"
      register: file_check

    - name: Leer contenido del archivo
      command: cat "{{ local_tmp_file }}"
      register: machines_text
      changed_when: false
      failed_when: false
      when: file_check.stat.exists

    - name: Enviar alerta si hay máquinas sin registrar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ⚠️ Citrix - Máquinas NO registradas
            Servidor: srv-ddc01
            Fecha: {{ current_time }}

            {{ machines_text.stdout }}
        status_code: 200
      when:
        - file_check.stat.exists
        - machines_text.stdout | length > 0

    - name: Enviar OK si todas están registradas
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ✅ Citrix OK
            Todas las máquinas están registradas correctamente.
            Servidor: srv-ddc01
            Fecha: {{ current_time }}
        status_code: 200
      when:
        - file_check.stat.exists
        - machines_text.stdout | length == 0

    - name: Mostrar mensaje si el archivo no existe
      debug:
        msg: "Archivo de máquinas no registradas no encontrado. Ejecuta primero la plantilla de fetch."
      when: not file_check.stat.exists
