---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no
  connection: local

  vars:
    tmp_artifact_file: "/tmp/unregistered_machines.txt"

  tasks:

    - name: Leer artifact generado por Job 1
      slurp:
        src: "{{ tmp_artifact_file }}"
      register: reporte_tmp

    - name: Convertir contenido de base64 a texto
      set_fact:
        reporte_texto: "{{ reporte_tmp.content | b64decode }}"

    - name: Debug - revisar contenido que se enviará
      debug:
        msg: "{{ reporte_texto }}"

    - name: Enviar mensaje por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ reporte_texto }}"
        status_code: 200
