---
- name: Enviar reporte Citrix por Telegram
  hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: Enviar mensaje por Telegram usando artifact
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ hostvars['srv-ddc01'].unregistered_machines_report | default('ALL_REGISTERED') }}"
        status_code: 200
      run_once: true
