---
- name: Verificar registro de maquinas Citrix y notificar
  hosts: srv-ddc01
  gather_facts: no
  become: false

  tasks:
    - name: Obtener maquinas sin registrar
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          foreach ($m in $unregistered) {
            Write-Output "🖥 $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState) | IP: $($m.IPAddress)"
          }
        }
      register: unregistered
      changed_when: false

    - name: Enviar alerta si hay maquinas sin registrar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ⚠️ Citrix - Máquinas NO registradas
            Servidor: {{ inventory_hostname }}

            {{ unregistered.stdout }}
        status_code: 200
      delegate_to: localhost
      when: unregistered.stdout is defined and unregistered.stdout | trim | length > 0

    - name: Enviar OK si todas estan registradas
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ✅ Citrix OK
            Todas las máquinas están registradas correctamente.
            Servidor: {{ inventory_hostname }}
        status_code: 200
      delegate_to: localhost
      when: unregistered.stdout is not defined or unregistered.stdout | trim | length == 0
