---
- name: Verificar registro de máquina virtual en Citrix
  hosts: srv-ctxp101
  gather_facts: yes
  
  tasks:
    - name: Verificar si el servicio Citrix VDA está corriendo
      ansible.windows.win_service:
        name: "BrokerAgent"
      register: citrix_service
      ignore_errors: yes

    - name: Obtener información del servicio Citrix Desktop Service
      ansible.windows.win_service_info:
        name: "BrokerAgent"
      register: service_info
      ignore_errors: yes

    - name: Ejecutar comando PowerShell para verificar registro
      ansible.windows.win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $machine = Get-BrokerMachine -MachineName "$env:COMPUTERNAME" -ErrorAction SilentlyContinue
        if ($machine) {
          Write-Output "Estado de Registro: $($machine.RegistrationState)"
          Write-Output "Estado de Energía: $($machine.PowerState)"
          Write-Output "Catálogo: $($machine.CatalogName)"
          Write-Output "Delivery Group: $($machine.DesktopGroupName)"
        } else {
          Write-Output "ERROR: Máquina no encontrada en Citrix"
        }
      register: citrix_status
      ignore_errors: yes
      delegate_to: localhost
      become: false

    - name: Verificar conectividad con el Delivery Controller
      ansible.windows.win_shell: |
        $regPath = "HKLM:\SOFTWARE\Citrix\VirtualDesktopAgent"
        if (Test-Path $regPath) {
          $controllers = (Get-ItemProperty -Path $regPath -Name "ListOfDDCs" -ErrorAction SilentlyContinue).ListOfDDCs
          Write-Output "Controladores configurados: $controllers"
        } else {
          Write-Output "ERROR: No se encuentra la configuración del VDA"
        }
      register: controller_info
      ignore_errors: yes

    - name: Preparar mensaje de Telegram
      set_fact:
        telegram_message: |
          🖥️ *Verificación Citrix - srv-ctxp101*
          
          *Servicio VDA:*
          {% if citrix_service.exists is defined and citrix_service.exists %}
          ✅ Estado: {{ service_info.services[0].state | default('Desconocido') }}
          ✅ Startup: {{ service_info.services[0].start_mode | default('Desconocido') }}
          {% else %}
          ❌ Servicio no encontrado
          {% endif %}
          
          *Estado de Registro:*
```
          {{ citrix_status.stdout | default('No se pudo obtener información') }}
```
          
          *Controladores:*
```
          {{ controller_info.stdout | default('No disponible') }}
```
          
          *Fecha:* {{ ansible_date_time.iso8601 }}
      delegate_to: localhost

    - name: Enviar resumen por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: form-urlencoded
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
          parse_mode: "Markdown"
      delegate_to: localhost
      become: false