---
############################################################
# PLAY 1 - Obtener VMs Citrix desde vCenter
############################################################
- name: Obtener VMs Citrix desde vCenter
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.alter.es"
    validate_certs: no
    cluster_name: "CL_CITRIX"
    vm_prefix: "SRV-CTXP"
    vm_start: 101
    vm_end: 145

  tasks:

    - name: Obtener TODAS las VMs del vCenter
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        show_cluster: true
      register: vms_info

    - name: Filtrar VMs del cluster CL_CITRIX y rango de nombre
      set_fact:
        citrix_vms: >-
          {{
            vms_info.virtual_machines
            | selectattr('cluster', 'defined')
            | selectattr('cluster', 'equalto', cluster_name)
            | selectattr('name', 'match', '^SRV-CTXP(1[0-4][0-9]|101)$')
            | list
          }}

    - name: Mostrar VMs detectadas
      debug:
        msg: "VM {{ item.name }} en cluster {{ item.cluster }}"
      loop: "{{ citrix_vms }}"
      loop_control:
        label: "{{ item.name }}"

############################################################
# PLAY 2 - Verificar registro en Citrix Director
############################################################
- name: Verificar registro de VMs en Citrix Director
  hosts: citrix_controllers
  gather_facts: no
  become: false

  tasks:

    - name: Comprobar estado de registro en Citrix Director (optimizado)
      win_shell: |
        Add-PSSnapin Citrix.*

        $vm_names = @( 
          {% for i in range(vm_start, vm_end + 1) %}
          "{{ vm_prefix }}{{ '%03d' % i }}"{% if not loop.last %}, {% endif %}
          {% endfor %}
        )

        $result = Get-BrokerMachine -MachineName $vm_names -ErrorAction SilentlyContinue | 
                  Select-Object Name, RegistrationState, MachineCatalog, DesktopGroupName

        $result | ConvertTo-Json -Depth 4
      register: citrix_status

    - name: Filtrar VMs no registradas
      set_fact:
        vms_no_registradas: >-
          {{
            (citrix_status.stdout | from_json)
            | selectattr('RegistrationState', 'ne', 'Registered')
            | list
          }}

    - name: Preparar mensaje de Telegram
      set_fact:
        telegram_message: >-
          {%- if vms_no_registradas | length > 0 -%}
          ⚠️ *VMs NO registradas en Citrix Director:*
          {%- for vm in vms_no_registradas -%}
          - {{ vm.Name }} (Estado: {{ vm.RegistrationState }})
          {%- endfor -%}
          {%- else -%}
          ✅ Todas las VMs están registradas correctamente.
          {%- endif -%}

    - name: Enviar notificación por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: form-urlencoded
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
          parse_mode: "Markdown"
      delegate_to: localhost
      become: false
