---
############################################################
# PLAY 1 - Obtener VMs Citrix desde vCenter (sin fechas)
############################################################
- name: Obtener VMs Citrix desde vCenter
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.alter.es"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_password }}"
    validate_certs: no
    cluster_name: "CL_CITRIX"

  tasks:

    - name: Obtener TODAS las VMs del vCenter
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        show_cluster: true
      register: vms_info

    - name: Filtrar VMs del cluster CL_CITRIX
      set_fact:
        citrix_vms: >-
          {{
            vms_info.virtual_machines
            | selectattr('cluster', 'defined')
            | selectattr('cluster', 'equalto', cluster_name)
            | list
          }}

    - name: Mostrar VMs detectadas
      debug:
        msg: "VM {{ item.name }} en cluster {{ item.cluster }}"
      loop: "{{ citrix_vms }}"
      loop_control:
        label: "{{ item.name }}"

############################################################
# PLAY 2 - Verificar registro en Citrix Director
############################################################
- name: Verificar registro de VMs en Citrix Director
  hosts: citrix_controllers
  gather_facts: no
  become: false

  vars:
    telegram_bot_token: "TU_BOT_TOKEN"
    telegram_chat_id: "TU_CHAT_ID"

  tasks:

    - name: Comprobar estado de registro en Citrix Director
      win_shell: |
        Add-PSSnapin Citrix.*
        $result = @()

        {% for vm in hostvars['localhost'].citrix_vms %}
        $m = Get-BrokerMachine -MachineName "{{ vm.name }}" -ErrorAction SilentlyContinue
        if ($m) {
          $result += [PSCustomObject]@{
            Name              = $m.Name
            RegistrationState = $m.RegistrationState
            MachineCatalog    = $m.MachineCatalog
            DeliveryGroup     = $m.DesktopGroupName
          }
        }
        {% endfor %}

        $result | ConvertTo-Json -Depth 4
      register: citrix_status

    - name: Mostrar estado Citrix
      debug:
        var: citrix_status.stdout

    - name: Filtrar VMs no registradas
      set_fact:
        vms_no_registradas: >-
          {{
            (citrix_status.stdout | from_json)
            | selectattr('RegistrationState', 'ne', 'Registered')
            | list
          }}

    - name: Mostrar VMs no registradas
      debug:
        var: vms_no_registradas

    - name: Notificar por Telegram VMs no registradas
      community.general.telegram:
        token: "{{ telegram_bot_token }}"
        chat_id: "{{ telegram_chat_id }}"
        msg: >-
          {%- if vms_no_registradas | length > 0 -%}
          ⚠️ VMs NO registradas en Citrix Director:
          {%- for vm in vms_no_registradas -%}
          - {{ vm.Name }} (Estado: {{ vm.RegistrationState }})
          {%- endfor -%}
          {%- else -%}
          ✅ Todas las VMs están registradas correctamente.
          {%- endif -%}
