---
- name: Verificar máquinas Citrix y enviar Telegram
  hosts: all
  gather_facts: no
  become: false

  vars:
    windows_tmp_file: "C:\\Temp\\unregistered_machines.txt"  # Ruta real en Windows
    local_tmp_file: "/tmp/unregistered_machines.txt"          # Mismo nombre para Linux/AWX
    current_time: "{{ '%Y-%m-%d %H:%M' | strftime }}"

  tasks:

    # ============================
    # BLOQUE WINDOWS: solo para srv-ddc01
    # ============================
    - block:
        - name: Obtener máquinas sin registrar y guardar en C:\Temp
          win_shell: |
            Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
            $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

            if ($unregistered) {
              $lines = @()
              foreach ($m in $unregistered) {
                $ip = if ($m.IPAddress) { $m.IPAddress } else { "-" }
                $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState) | IP: $ip"
              }
              $lines -join "`n"
            } else {
              "ALL_REGISTERED"
            }
          register: unregistered_machines
          changed_when: false

        - name: Guardar contenido en archivo temporal en Windows
          win_copy:
            content: "{{ unregistered_machines.stdout | default('ALL_REGISTERED') }}"
            dest: "{{ windows_tmp_file }}"
      when: "'srv-ddc01' in inventory_hostname"

    # ============================
    # BLOQUE LOCALHOST: traer archivo y enviar Telegram
    # ============================
    - block:
        - name: Traer archivo desde Windows
          fetch:
            src: "{{ windows_tmp_file }}"
            dest: "{{ local_tmp_file }}"
            flat: yes
          delegate_to: "{{ inventory_hostname }}"

        - name: Leer contenido del archivo
          slurp:
            src: "{{ local_tmp_file }}"
          register: machines_content

        - name: Decodificar contenido
          set_fact:
            machines_text: "{{ machines_content.content | b64decode | trim }}"

        - name: Enviar alerta Telegram si hay máquinas sin registrar
          uri:
            url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
            method: POST
            body_format: json
            body:
              chat_id: "{{ telegram_chat_id }}"
              text: |
                ⚠️ Citrix - Máquinas NO registradas
                Servidor: {{ inventory_hostname }}
                Fecha: {{ current_time }}

                {{ machines_text }}
            status_code: 200
          when: machines_text != "ALL_REGISTERED"
          delegate_to: localhost

        - name: Enviar OK Telegram si todas están registradas
          uri:
            url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
            method: POST
            body_format: json
            body:
              chat_id: "{{ telegram_chat_id }}"
              text: |
                ✅ Citrix OK
                Todas las máquinas están registradas correctamente.
                Servidor: {{ inventory_hostname }}
                Fecha: {{ current_time }}
            status_code: 200
          when: machines_text == "ALL_REGISTERED"
          delegate_to: localhost
      run_once: true
