---
- name: Verificar maquinas sin registrar en Citrix
  hosts: srv-ddc01
  gather_facts: yes
  become: false

  tasks:

    - name: Consultar todas las maquinas sin registrar en Citrix Studio
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue
        if ($unregistered) {
          Write-Output "=== MAQUINAS SIN REGISTRAR ==="
          Write-Output "Total: $($unregistered.Count)"
          foreach ($machine in $unregistered) {
            Write-Output "Nombre: $($machine.MachineName)"
            Write-Output "Catalogo: $($machine.CatalogName)"
            Write-Output "Delivery Group: $($machine.DesktopGroupName)"
            Write-Output "Estado Energia: $($machine.PowerState)"
            Write-Output "IP: $($machine.IPAddress)"
            Write-Output "Sesiones: $($machine.SessionCount)"
            Write-Output "-----------------------------"
          }
        } else {
          Write-Output "=== MAQUINAS SIN REGISTRAR ==="
          Write-Output "Total: 0"
          Write-Output "Todo OK"
        }
      register: unregistered_machines

    - name: Consultar resumen general de Delivery Groups
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $allDG = Get-BrokerDesktopGroup
        Write-Output "=== RESUMEN DELIVERY GROUPS ==="
        foreach ($dg in $allDG) {
          $unregCount = $dg.TotalMachines - $dg.MachinesRegistered
          Write-Output "Grupo: $($dg.Name)"
          Write-Output "  Total: $($dg.TotalMachines)"
          Write-Output "  Registradas: $($dg.MachinesRegistered)"
          Write-Output "  Sin Registrar: $unregCount"
          Write-Output "  Sesiones: $($dg.Sessions)"
          Write-Output "---"
        }
      register: delivery_groups_summary
      ignore_errors: yes

    - name: Consultar total de maquinas registradas
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $registered = Get-BrokerMachine -RegistrationState Registered
        Write-Output "=== MAQUINAS REGISTRADAS ==="
        Write-Output "Total: $($registered.Count)"
      register: registered_count
      ignore_errors: yes

    - name: Enviar resumen por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            📊 REPORTE CITRIX STUDIO

            Servidor: {{ inventory_hostname }}
            Fecha: {{ ansible_date_time.iso8601 }}

            {{ registered_count.stdout }}

            {{ unregistered_machines.stdout }}

            {{ delivery_groups_summary.stdout }}
        status_code: 200
      delegate_to: localhost
      run_once: true
