---
############################################################
# PLAY ÚNICO - Verificar registro en Citrix Director
############################################################
- name: Verificar registro de VMs en Citrix Director
  hosts: citrix_controllers
  gather_facts: no
  become: false

  vars:
    vm_prefix: "SRV-CTXP"
    vm_start: 101
    vm_end: 145

  tasks:

    - name: Comprobar estado de registro en Citrix Director
      win_shell: |
        Add-PSSnapin Citrix.*

        # Generar la lista de nombres de VM
        $vm_names = @(
          {% for i in range(vm_start, vm_end + 1) %}
          "{{ vm_prefix }}{{ '%03d' % i }}"{% if not loop.last %}, {% endif %}
          {% endfor %}
        )

        # Obtener estado de registro de todas las VMs
        $result = Get-BrokerMachine -MachineName $vm_names -ErrorAction SilentlyContinue | 
                  Select-Object Name, RegistrationState, MachineCatalog, DesktopGroupName

        $result | ConvertTo-Json -Depth 4
      register: citrix_status

    - name: Filtrar VMs no registradas
      set_fact:
        vms_no_registradas: >-
          {{
            (citrix_status.stdout | from_json)
            | selectattr('RegistrationState', 'ne', 'Registered')
            | list
          }}

    - name: Preparar mensaje de Telegram
      set_fact:
        telegram_message: >-
          {%- if vms_no_registradas | length > 0 -%}
          ⚠️ *VMs NO registradas en Citrix Director:*
          {%- for vm in vms_no_registradas -%}
          - {{ vm.Name }} (Estado: {{ vm.RegistrationState }})
          {%- endfor -%}
          {%- else -%}
          ✅ Todas las VMs están registradas correctamente.
          {%- endif -%}

    - name: Enviar notificación por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: form-urlencoded
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
          parse_mode: "Markdown"
      delegate_to: localhost
      become: false
