---
- name: Verificar máquinas Citrix y notificar por Telegram
  hosts: srv-ddc01
  gather_facts: no
  become: false

  vars:
    current_time: "{{ '%Y-%m-%d %H:%M' | strftime }}"
    tmp_file: "C:\\Temp\\unregistered_machines.txt"       # Cambiado a C:\Temp
    local_tmp_file: "/tmp/unregistered_machines_{{ inventory_hostname }}.txt"

  tasks:

    # ============================
    # 1️⃣ Windows: generar archivo temporal
    # ============================
    - name: Obtener máquinas sin registrar y guardar en archivo
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          $lines = @()
          foreach ($m in $unregistered) {
            $ip = if ($m.IPAddress) { $m.IPAddress } else { "-" }
            $lines += "🖥 Name: $($m.MachineName) | State: $($m.RegistrationState) | Power: $($m.PowerState) | IP: $ip"
          }
          $lines -join "`n"
        } else {
          "ALL_REGISTERED"
        }
      register: unregistered_machines
      changed_when: false

    - name: Guardar contenido en archivo temporal en Windows
      win_copy:
        content: "{{ unregistered_machines.stdout | default('ALL_REGISTERED') }}"
        dest: "{{ tmp_file }}"

    # ============================
    # 2️⃣ AWX/Linux: traer archivo
    # ============================
    - name: Traer archivo temporal a AWX/Linux
      fetch:
        src: "{{ tmp_file }}"
        dest: "{{ local_tmp_file }}"
        flat: yes

    - name: Comprobar que archivo existe
      stat:
        path: "{{ local_tmp_file }}"
      register: file_check

    - name: Fail si archivo no existe
      fail:
        msg: "El archivo temporal no se ha traído desde Windows."
      when: not file_check.stat.exists

    - name: Leer contenido del archivo
      slurp:
        src: "{{ local_tmp_file }}"
      register: machines_content

    - name: Decodificar contenido
      set_fact:
        machines_text: "{{ machines_content.content | b64decode | trim }}"

    # ============================
    # 3️⃣ Enviar mensaje Telegram
    # ============================
    - name: Enviar alerta Telegram si hay máquinas sin registrar
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ⚠️ Citrix - Máquinas NO registradas
            Servidor: {{ inventory_hostname }}
            Fecha: {{ current_time }}

            {{ machines_text }}
        status_code: 200
      when: machines_text != "ALL_REGISTERED"
      delegate_to: localhost

    - name: Enviar OK Telegram si todas están registradas
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: json
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: |
            ✅ Citrix OK
            Todas las máquinas están registradas correctamente.
            Servidor: {{ inventory_hostname }}
            Fecha: {{ current_time }}
        status_code: 200
      when: machines_text == "ALL_REGISTERED"
      delegate_to: localhost
