---
- name: Mostrar maquinas sin registrar en Citrix
  hosts: srv-ddc01
  gather_facts: no
  become: false

  tasks:
    - name: Obtener maquinas sin registrar en Citrix Studio
      win_shell: |
        Add-PSSnapin Citrix.Broker.Admin.V2 -ErrorAction SilentlyContinue
        $unregistered = Get-BrokerMachine -RegistrationState Unregistered -ErrorAction SilentlyContinue

        if ($unregistered) {
          foreach ($machine in $unregistered) {
            Write-Output "Nombre: $($machine.MachineName)"
            Write-Output "Catalogo: $($machine.CatalogName)"
            Write-Output "Delivery Group: $($machine.DesktopGroupName)"
            Write-Output "Estado Energia: $($machine.PowerState)"
            Write-Output "IP: $($machine.IPAddress)"
            Write-Output "Sesiones: $($machine.SessionCount)"
            Write-Output "----------------------------------------"
          }
        } else {
          Write-Output "No hay maquinas sin registrar - Todo OK"
        }
      register: unregistered_machines

    - name: Mostrar resultado en consola
      debug:
        msg: "{{ unregistered_machines.stdout }}"
