---
############################################################
# PLAY 1 - Detectar VMs Citrix reiniciadas en vCenter
############################################################
- name: Detectar VMs Citrix reiniciadas en vCenter
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.alter.es"
    vcenter_user: "{{ vcenter_user }}"
    vcenter_password: "{{ vcenter_password }}"
    validate_certs: no

    cluster_name: "CL_CITRIX"
    last_boot_minutes: 10

  tasks:

    - name: Obtener TODAS las VMs del vCenter
      community.vmware.vmware_vm_info:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        show_cluster: true
      register: vms_info

    - name: Filtrar VMs del cluster CL_CITRIX reiniciadas recientemente
      set_fact:
        restarted_vms: >-
          {{
            vms_info.virtual_machines
            | selectattr('cluster', 'defined')
            | selectattr('cluster', 'equalto', cluster_name)
            | selectattr('power_state', 'defined')
            | selectattr('power_state', 'equalto', 'poweredOn')
            | selectattr('boot_time', 'defined')
            | selectattr(
                'boot_time',
                '>=',
                (ansible_date_time.iso8601
                 | to_datetime('%Y-%m-%dT%H:%M:%SZ')
                 - timedelta(minutes=last_boot_minutes))
              )
            | list
          }}

    - name: Mostrar VMs filtradas
      debug:
        msg: "VM {{ item.name }} ({{ item.cluster }}) reiniciada en {{ item.boot_time }}"
      loop: "{{ restarted_vms }}"
      loop_control:
        label: "{{ item.name }}"

############################################################
# PLAY 2 - Verificar registro de VMs en Citrix Director
############################################################
- name: Verificar registro de VMs en Citrix Director
  hosts: citrix_controllers
  gather_facts: no
  become: false

  tasks:

    - name: Comprobar estado de VMs Citrix
      win_shell: |
        Add-PSSnapin Citrix.*
        $result = @()

        {% for vm in hostvars['localhost'].restarted_vms %}
        $m = Get-BrokerMachine -MachineName "{{ vm.name }}" -ErrorAction SilentlyContinue
        if ($m) {
          $result += [PSCustomObject]@{
            Name              = $m.Name
            RegistrationState = $m.RegistrationState
            MachineCatalog    = $m.MachineCatalog
            DeliveryGroup     = $m.DesktopGroupName
          }
        }
        {% endfor %}

        $result | ConvertTo-Json
      register: citrix_status

    - name: Mostrar resultado Citrix
      debug:
        var: citrix_status.stdout
