---
############################################################
# PLAY ÃšNICO - Verificar registro en Citrix Director
############################################################
- name: Verificar registro de VMs en Citrix Director
  hosts: srv-ctxp101
  gather_facts: no
  become: false

  vars:
    vm_prefix: "SRV-CTXP"
    vm_start: 101
    vm_end: 145

  tasks:

    - name: Comprobar estado de registro en Citrix Director
      win_shell: |
        Add-PSSnapin Citrix.*

        # Generar la lista de nombres de VM
        $vm_names = @(
          {% for i in range(vm_start, vm_end + 1) %}
          "{{ vm_prefix }}{{ '%03d' % i }}"{% if not loop.last %}, {% endif %}
          {% endfor %}
        )

        # Obtener estado de registro de todas las VMs
        $result = Get-BrokerMachine -MachineName $vm_names -ErrorAction SilentlyContinue | 
                  Select-Object Name, RegistrationState, MachineCatalog, DesktopGroupName

        $result | ConvertTo-Json -Depth 4
      register: citrix_status

    - name: Separar VMs registradas y no registradas
      set_fact:
        vms_registradas: >-
          {{
            (citrix_status.stdout | from_json)
            | selectattr('RegistrationState', 'eq', 'Registered')
            | list
          }}
        vms_no_registradas: >-
          {{
            (citrix_status.stdout | from_json)
            | selectattr('RegistrationState', 'ne', 'Registered')
            | list
          }}

    - name: Preparar mensaje completo para Telegram
      set_fact:
        telegram_message: >-
          ðŸ–¥ *Resumen de VMs Citrix Director*

          âœ… *Registradas ({{ vms_registradas | length }}):*
          {%- for vm in vms_registradas %}
          - {{ vm.Name }} (Estado: {{ vm.RegistrationState }})
          {%- endfor %}

          âš ï¸ *No registradas ({{ vms_no_registradas | length }}):*
          {%- if vms_no_registradas | length > 0 %}
          {%- for vm in vms_no_registradas %}
          - {{ vm.Name }} (Estado: {{ vm.RegistrationState }})
          {%- endfor %}
          {%- else %}
          Ninguna
          {%- endif %}

    - name: Enviar resumen por Telegram
      uri:
        url: "https://api.telegram.org/bot{{ telegram_bot_token }}/sendMessage"
        method: POST
        body_format: form-urlencoded
        body:
          chat_id: "{{ telegram_chat_id }}"
          text: "{{ telegram_message }}"
          parse_mode: "Markdown"
      delegate_to: localhost
      become: false
