---
- name: Recuperar VMs Citrix desde VMware
  hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "vcenter.alter.es"
    vcenter_validate_certs: false
    datacenter_name: "ALTER-DC"   # ajusta si aplica

    # Variables heredadas del workflow
    citrix_powered_on: "{{ citrix_powered_on | default([]) }}"
    citrix_restarted: "{{ citrix_restarted | default([]) }}"

  tasks:

    - name: Unir todas las VMs no registradas
      set_fact:
        vms_afectadas: "{{ citrix_powered_on + citrix_restarted }}"

    - name: Mostrar VMs a procesar
      debug:
        var: vms_afectadas

    - name: Encender VMs apagadas en vCenter
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ item }}"
        state: powered-on
      loop: "{{ citrix_powered_on }}"
      when: citrix_powered_on | length > 0

    - name: Reinicio forzado de VMs encendidas (reset)
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ item }}"
        state: restarted
      loop: "{{ citrix_restarted }}"
      when: citrix_restarted | length > 0
