---
- name: Reiniciar VMs Citrix Unregistered vía WinRM
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Verificar si hay VMs Unregistered
      debug:
        msg: "VMs a reiniciar: {{ citrix_on_unregistered }}"
      when: citrix_on_unregistered is defined

    - name: Añadir VMs Unregistered al grupo dinámico
      add_host:
        name: "{{ item }}"
        groups: citrix_unregistered
      loop: "{{ citrix_on_unregistered | default([]) }}"

- name: Reiniciar VMs Citrix Unregistered vía WinRM
  hosts: citrix_unregistered
  gather_facts: no
  serial: 1
  any_errors_fatal: false

  tasks:

    - name: Comprobar conectividad WinRM
      win_ping:

    - name: Reiniciar servidor Windows
      win_reboot:
        reboot_timeout: 900
        msg: "Reinicio automático por VM Citrix Unregistered"
        post_reboot_delay: 60

    - name: Esperar a que vuelva WinRM
      wait_for_connection:
        timeout: 600
