- name: Preparar hosts Citrix Unregistered
  hosts: localhost
  gather_facts: no

  tasks:

    - name: Ver variable recibida desde el workflow
      debug:
        var: citrix_restarted

    - name: Limpiar nombres de host (quitar dominio)
      set_fact:
        citrix_hosts_limpios: >-
          {{
            (citrix_restarted | default([])) 
            | map('regex_replace', '^.*\\\\\\\\', '') 
            | list
          }}
      when: citrix_restarted | length > 0

    - name: No hay VMs para reiniciar
      debug:
        msg: "No se encontraron VMs Unregistered para reiniciar"
      when: citrix_restarted | length == 0

    - name: Mostrar hosts finales a reiniciar
      debug:
        var: citrix_hosts_limpios
      when: citrix_restarted | length > 0

    - name: Añadir VMs Unregistered al grupo dinámico
      add_host:
        name: "{{ item }}"
        groups: citrix_unregistered
        ansible_host: "{{ item | lower }}.alter.es"
      loop: "{{ citrix_hosts_limpios }}"
      when: citrix_restarted | length > 0
